
project_id = "jpelncawdaounkidvymu"

[functions]
[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-webhook.environment]
STRIPE_WEBHOOK_SECRET = "whsec_3NBhwaToGSYUQq2XtjKPrwG1aRDpscrM"
STRIPE_WEBHOOK_SECRET_TEST = "whsec_mxduieTaBI8bMyVlioaNGFjSYX5tDhii"
GA4_API_SECRET = "sZeGSAYwR1uvsvLZJJsajw" 
GA4_MEASUREMENT_ID = "G-qAS5OCTURaCmQ1IfJY2ScQ"
DATAFAST_WEBSITE_ID = "67ecaee943c67e6831381271"
