[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  BRANCH = "Second-branch"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200