
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  BRANCH = "Second-branch"

# Redirect root to bienvenue page
[[redirects]]
  from = "/"
  to = "/bienvenue"
  status = 301

# Redirect old home to tableaudebord
[[redirects]]
  from = "/home"
  to = "/tableaudebord"
  status = 301

[[redirects]]
  from = "/t20/*"
  to = "/.netlify/functions/redirect/t20/:splat"
  status = 302

[[redirects]]
  from = "/t40/*"
  to = "/.netlify/functions/redirect/t40/:splat"
  status = 302

[[redirects]]
  from = "/i20/*"
  to = "/.netlify/functions/redirect/i20/:splat"
  status = 302

[[redirects]]
  from = "/i40/*"
  to = "/.netlify/functions/redirect/i40/:splat"
  status = 302

[[redirects]]
  from = "/r/*"
  to = "/.netlify/functions/redirect/r/:splat"
  status = 302

[[redirects]]
  from = "/tt"
  to = "/.netlify/functions/redirect/tt"
  status = 302

[[redirects]]
  from = "/fb"
  to = "/.netlify/functions/redirect/fb"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
